### ISSUE TITLE
What is the role of f_bar ？

### ISSUE THREAD

**Issue by wuxiyu** [npow/memnn#6]
```
cost_arr[2*i], _ = theano.scan(lambda f_bar, t: T.switch(T.or_(T.eq(t, f[i]), T.eq(t, T.shape(L)[0]-1)), 0, T.largest(gamma - s_Ot(T.stack(*m[:i+1]), f[i], t, L), 0)),
                                           sequences=[L, T.arange(T.shape(L)[0])])
```

It seem to do nothing?

**Comment by npow** [comment]
`f_bar` is equal to `f[i]` when `t != f[i]`. I just wrote the equation in a convoluted manner.

![image](https://cloud.githubusercontent.com/assets/206201/23222141/de13589e-f8db-11e6-9c11-96dd8ca12616.png)
