### ISSUE TITLE
What does n_wrong and refs mean? Thank you !

### ISSUE THREAD

**Issue by guotong1988** [npow/memnn#7]
@npow  Thank you. 

https://github.com/npow/MemNN/blob/master/main.py#L138
` print "i: ", i, " nwrong: ", n_wrong`

   
https://github.com/npow/MemNN/blob/master/main.py#L140
`refs = line['refs']`

**Comment by guotong1988** [comment]
Oh , `refs` means the line of the answer word.

**Comment by npow** [comment]
`n_wrong` is the number of wrong answers.
IIRC `refs` is the set of previous statements that the question is referring to.
